#!/usr/bin/env bash

set -e

export SHELL="/bin/bash"

BASEDIR="$(cd "$(dirname "$BASH_SOURCE[0]")" && pwd)"
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bit/dotbot"

cd "$BASEDIR"
git -C "$DOTBOT_DIR" submodule sync --quiet --recursive
git submodule update --init --recursive "$DOTBOT_DIR"

run_dotbot() {
    local config
    config="$1"

    "$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
    -d "$BASEDIR" \
    -c "$config" $ARGS
}

run_dotbot "steps/fonts.yml" || true
